<h3 style="text-align: left; background-color: #e0e0e0; font-family:Times New Roman; color: black; padding: 14px; line-height: 1; border-radius:10px">Effectuer une opération scalaire</h3>

Effectuer une opération scalaire avec NumPy signifie appliquer une opération mathématique (comme l'addition, la soustraction, la multiplication ou la division) sur chaque élément d'un tableau avec une valeur scalaire (un seul nombre)

In [19]:
import numpy as np

In [20]:
array = np.array([1, 2, 3, 4, 5])

In [21]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

#### Addition

In [22]:
# Ajouter un scalaire à chaque élément
resultat = array + 10
print(array)
print(resultat)

[1 2 3 4 5]
[11 12 13 14 15]


In [23]:
resultat = array_2d + 5
print(array_2d)
print(resultat)

[[1 2 3]
 [4 5 6]]
[[ 6  7  8]
 [ 9 10 11]]


#### Soustraction

In [24]:
# Soustraire un scalaire à chaque élément
resultat = array - 2
print(array)
print(resultat)

[1 2 3 4 5]
[-1  0  1  2  3]


#### Multiplication

In [25]:
# Multiplier chaque élément par un scalaire
resultat = array * 10
print(array)
print(resultat)  

[1 2 3 4 5]
[10 20 30 40 50]


#### Division

In [26]:
# Diviser chaque élément par un scalaire
resultat = array / 2.5
print(array)
print(resultat)

[1 2 3 4 5]
[0.4 0.8 1.2 1.6 2. ]


In [27]:
# Récupérer le quotient entier d'une division
resultat = array // 2
print(array)
print(resultat)

[1 2 3 4 5]
[0 1 1 2 2]


In [28]:
# Récupérer le reste de la division
resultat = array % 2
print(array)
print(resultat)

[1 2 3 4 5]
[1 0 1 0 1]
