<h3 style="text-align: left; background-color: #e0e0e0; font-family:Times New Roman; color: black; padding: 14px; line-height: 1; border-radius:10px">La fonction median()</h3>

La fonction median() de NumPy est utilisée pour calculer la médiane des éléments d'un array. La médiane est une valeur qui sépare les données en deux parties égales : la moitié des valeurs est inférieure à la médiane, et l'autre moitié est supérieure. 

Deux possibilités :   
    - soit le nombre d'éléments est pair, la médiane est donc la moyenne des deux valeurs "centrales"  
    exemple : [1, 2, 3, 4] a une médiane de 2,5  
    - soit le nombre d'éléments est impair, la médiane est la valeur centrale   
    exemple : [1, 2, 3, 4, 5] a une médiane de 3

In [7]:
import numpy as np

In [8]:
array_1d = np.array([1, 3, 5, 7, 9])

mediane = np.median(array_1d)
print(mediane) 

5.0


In [9]:
array_1d = np.array([1, 3, 5, 7, 9, 11])

mediane = np.median(array_1d)
print(mediane) 

6.0


In [10]:
array_2d = np.array([[10, 20, 30], [5, 15, 25], [8, 18, 28]])
print(array_2d)

# Médiane de tous les éléments
mediane_totale = np.median(array_2d)
print("la médiane de tous les éléments est:", mediane_totale)  

# Médiane par colonne (axis=0)
mediane_colonnes = np.median(array_2d, axis=0)
print("la médiane de par colonne est:", mediane_colonnes)  

# Médiane par ligne (axis=1)
mediane_lignes = np.median(array_2d, axis=1)
print("la médiane par ligne est:",mediane_lignes) 

[[10 20 30]
 [ 5 15 25]
 [ 8 18 28]]
la médiane de tous les éléments est: 18.0
la médiane de par colonne est: [ 8. 18. 28.]
la médiane par ligne est: [20. 15. 18.]
