<h3 style="text-align: left; background-color: #e0e0e0; font-family:Times New Roman; color: black; padding: 14px; line-height: 1; border-radius:10px">La fonction quantile()</h3>

La fonction quantile() de NumPy est utilisée pour calculer les quantiles d'un array, c'est-à-dire les valeurs qui divisent un ensemble de données en intervalles de même fréquence

In [8]:
import numpy as np

In [9]:
array = np.array([1, 2, 3, 4, 5])

# 50e percentile (médiane)
quantile_50 = np.quantile(array, 0.5)
print(quantile_50)  

3.0


In [10]:
# 25e percentile (1er quartile)
quantile_25 = np.quantile(array, 0.25)
print(array)
print(quantile_25)  

[1 2 3 4 5]
2.0


In [11]:
# 75e percentile (3er quartile)
quantile_75 = np.quantile(array, 0.75)
print(array)
print(quantile_75)  

[1 2 3 4 5]
4.0


In [12]:
quartiles = np.quantile(array, [0.25, 0.5, 0.75])
print(quartiles)  

[2. 3. 4.]


In [13]:
array_2d = np.array([[10, 20, 30], [15, 25, 35], [5, 15, 25]])

# 50e percentile (médiane) de tous les éléments
quantile_50_total = np.quantile(array_2d, 0.5)
print(quantile_50_total)  

20.0


In [14]:
# 50e percentile par colonne (axis=0)
quantile_colonnes = np.quantile(array_2d, 0.5, axis=0)
print(array_2d)
print(quantile_colonnes)

[[10 20 30]
 [15 25 35]
 [ 5 15 25]]
[10. 20. 30.]
