<h3 style="text-align: left; background-color: #e0e0e0; font-family:Times New Roman; color: black; padding: 14px; line-height: 1; border-radius:10px">La fonction mean()</h3>

La fonction mean() de NumPy est utilisée pour calculer la moyenne arithmétique des éléments d'un array. Par définition, la moyenne est la somme des valeurs divisée par le nombre total de valeurs.

In [10]:
import numpy as np

In [11]:
array = np.array([1, 2, 3, 4, 5])

# Calcul de la moyenne
moyenne = np.mean(array)
print(moyenne)  

3.0


In [12]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

# Calculer la moyenne de tous les éléments
moyenne_totale = np.mean(array_2d)
print("La moyenne de tous les éléments est :",moyenne_totale)  

# Moyenne par colonne (axis=0)
moyenne_colonnes = np.mean(array_2d, axis=0)
print("La moyenne par colonne est :", moyenne_colonnes)  

# Moyenne par ligne (axis=1)
moyenne_lignes = np.mean(array_2d, axis=1)
print("La moyenne par ligne est :", moyenne_lignes)  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
La moyenne de tous les éléments est : 5.0
La moyenne par colonne est : [4. 5. 6.]
La moyenne par ligne est : [2. 5. 8.]
