<h3 style="text-align: left; background-color: #e0e0e0; font-family:Times New Roman; color: black; padding: 14px; line-height: 1; border-radius:10px">Créer un array avec NumPy</h3>

In [1]:
# Importer la bibliothèque NumPy
import numpy as np

In [2]:
mon_array = np.array([1, 2, 3, 4, 5])
print(mon_array)  

[1 2 3 4 5]


In [3]:
mon_array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(mon_array_2d)

[[1 2 3]
 [4 5 6]]
